import { Category, InventoryItem } from "./types";

export const categories: Category[] = [
  { id: "books", name: "Shade Books & Fan Deck", hindiName: "शेड बुक और फैन डेक", description: "Interior, exterior, texture and enamel books, colour palettes and fan deck must stay complete, clean and available at the display.", photo: "/reference/51880.jpg", owner: "Store Manager" },
  { id: "enamel", name: "Enamel Paint & Device Station", hindiName: "एनामेल पेंट और डिवाइस स्टेशन", description: "Arrange Luxol enamel products by type and pack size. Check printer ink and paper, charge all devices before closing, and organise paint files, catalogues and documents daily.", photo: "/reference/51886.jpg", owner: "Store Manager" },
  { id: "stainer-colour-bank", name: "Stainer, Mini Luxol & Colour Bank", hindiName: "स्टेनर, मिनी लक्सोल और कलर बैंक", description: "Zone A: monitor stainer cartons and add any box below 20% to the order book. Zone B: keep Luxol packs below 200 ml sorted and available. Zone C: verify every colour-bank inlet contains colour by opening the relevant cap while making colour, and keep colourant cans available on the rack above.", photo: "/reference/52297-annotated.jpg", owner: "Store Manager" },
  { id: "exterior-paint", name: "Exterior Paint Rack", hindiName: "एक्सटीरियर पेंट रैक", description: "Sort exterior products by product family and pack size. Keep primer only in the designated bottom two rows and maintain sufficient display stock.", photo: "/reference/51885.jpg", owner: "Store Manager" },
  { id: "interior-paint", name: "Interior Paint Rack", hindiName: "इंटीरियर पेंट रैक", description: "Sort interior paints by product family, finish and pack size. Keep labels facing outward and refill empty display spaces.", photo: "/reference/51884.jpg", owner: "Store Manager" },
  { id: "waterproofing", name: "Waterproofing & New Arrival", hindiName: "वॉटरप्रूफिंग और न्यू अराइवल", description: "Keep Roof Kool & Seal, Dampstop Elasto, Dampstop Advanced and related waterproofing products fully displayed and ready for restocking.", photo: "/reference/51883.jpg", owner: "Store Manager" },
  { id: "wood-finishes", name: "Wood Finishes", hindiName: "वुड फिनिश सेक्शन", description: "Check melamine, GP thinner, Eco thinner, crack fill, sanding sealer, car patch and local turpentine. Arrange by type, keep containers upright and reorder before shelves become empty.", photo: "/reference/51881.jpg", owner: "Store Manager" },
  { id: "desk", name: "Working Desk", hindiName: "वर्किंग डेस्क", description: "Daily-use desk supplies: pens, markers, stapler, calculator, estimate pad, bill book and laptop readiness.", photo: "/reference/51892.jpg", owner: "Staff" },
  { id: "cash-token", name: "Cash & Token Drawer", hindiName: "कैश और टोकन", description: "Change notes, cash tokens, point tokens and customer diary entries must be reconciled.", photo: "/reference/51893.jpg", owner: "Store Manager" },
  { id: "stationery", name: "Stationery Drawer", hindiName: "स्टेशनरी ड्रॉअर", description: "Backup pens, punches, staplers, pins, stamps, batteries, tape and new notebooks.", photo: "/reference/51894.jpg", owner: "Staff" },
  { id: "polybag", name: "Poly Bags", hindiName: "पॉली बैग", description: "Packaging bags must always be available in working quantity.", photo: "/reference/51895.jpg", owner: "Store Manager" },
  { id: "rental", name: "Rental Register", hindiName: "रेंटल रजिस्टर", description: "Continue the physical rental register until the workflow is fully migrated into the app.", photo: "/reference/51896.jpg", owner: "Store Manager" },
  { id: "invoices", name: "GST & Temporary Bills", hindiName: "GST और कच्चे बिल", description: "Every purchase must have a GST invoice, temporary invoice, or self-created purchase record with payment details.", photo: "/reference/51897.jpg", owner: "Accounts" },
  { id: "rollers", name: "Rollers & Refills", hindiName: "रोलर और रिफिल", description: "Exterior/interior rollers and refills arranged by size with minimum stock control.", photo: "/reference/51889.jpg", owner: "Store Manager" },
  { id: "brushes", name: "Brushes, Sandpaper & Putty Blades", hindiName: "ब्रश, सैंडपेपर और पट्टी", description: "Wet/dry sandpaper, brushes, kalam brushes and putty blades sorted by size and grit.", photo: "/reference/51888.jpg", owner: "Store Manager" },
  { id: "rolls-stencils", name: "Abrasive Rolls & Stencils", hindiName: "रोल, स्टेंसिल और लाल चरी", description: "Abrasive rolls, wooden rolls, stencils and red cord stock with reorder control.", photo: "/reference/51887.jpg", owner: "Store Manager" },
  { id: "bulk-materials", name: "Daily Bulk Materials", hindiName: "दैनिक भारी सामान", description: "Level plast, chalk powder, putty, white cement, whiting, POP, wax, chowry and texture putty are checked separately every day.", photo: "/reference/51889.jpg", owner: "Store Manager" }
];

const make = (id: string, categoryId: string, name: string, unit: string, currentQty: number, minimumQty: number, targetQty: number, responsible: InventoryItem["responsible"], location: string, notes?: string): InventoryItem => ({
  id, categoryId, name, unit, currentQty, minimumQty, targetQty, responsible, location, notes
});

export const inventorySeed: InventoryItem[] = [
  make("interior-book", "books", "Interior shade book", "book", 1, 1, 2, "Store Manager", "Front display"),
  make("exterior-book", "books", "Exterior shade book", "book", 1, 1, 2, "Store Manager", "Front display"),
  make("texture-book", "books", "Texture book", "book", 1, 1, 2, "Store Manager", "Front display"),
  make("enamel-palette", "books", "Interior/Exterior enamel colour palette", "set", 1, 1, 2, "Store Manager", "Front display"),
  make("fan-deck", "books", "Fan deck", "set", 1, 1, 2, "Store Manager", "Front display"),

  make("luxol-hg-small", "enamel", "Luxol High Gloss enamel – small packs", "tin", 8, 6, 16, "Store Manager", "Enamel rack – upper shelf"),
  make("luxol-hg-medium", "enamel", "Luxol High Gloss enamel – medium packs", "tin", 7, 5, 12, "Store Manager", "Enamel rack – upper shelf"),
  make("luxol-pu-small", "enamel", "Luxol PU enamel – small packs", "tin", 12, 8, 20, "Store Manager", "Enamel rack – second shelf"),
  make("luxol-pu-medium", "enamel", "Luxol PU enamel – medium packs", "tin", 8, 6, 14, "Store Manager", "Enamel rack – second shelf"),
  make("enamel-assorted", "enamel", "Other enamel and metal paint packs", "tin", 15, 10, 24, "Store Manager", "Enamel rack – lower shelves"),
  make("printer-black-ink", "enamel", "Printer black ink", "bottle", 1, 1, 2, "Staff", "Printer shelf", "Check ink level before store opening."),
  make("printer-colour-ink", "enamel", "Printer colour ink set", "set", 1, 1, 2, "Staff", "Printer shelf"),
  make("printer-paper-a4", "enamel", "A4 printer paper", "ream", 1, 2, 5, "Staff", "Printer shelf"),
  make("charging-board", "enamel", "Charging board functional", "point", 4, 4, 4, "Staff", "Device shelf", "All charging points must work."),
  make("devices-charged", "enamel", "Store devices charged before closing", "device", 2, 2, 2, "Staff", "Device shelf", "Complete every evening before leaving."),
  make("paint-files", "enamel", "Paint files and documents arranged", "file", 5, 5, 5, "Staff", "Enamel rack document shelf"),
  make("paint-catalogues", "enamel", "Paint catalogues arranged", "catalogue", 6, 5, 10, "Staff", "Enamel rack document shelf"),

  make("stainer-red-box", "stainer-colour-bank", "Stainer carton – red family", "% box", 65, 20, 100, "Store Manager", "Zone A – stainer shelf", "Enter the order book immediately when remaining stock falls below 20% of the carton."),
  make("stainer-yellow-box", "stainer-colour-bank", "Stainer carton – yellow family", "% box", 45, 20, 100, "Store Manager", "Zone A – stainer shelf", "Check carton balance visually; below 20% triggers reorder."),
  make("stainer-blue-box", "stainer-colour-bank", "Stainer carton – blue family", "% box", 18, 20, 100, "Store Manager", "Zone A – stainer shelf", "Below 20%: put into order book."),
  make("stainer-black-white-box", "stainer-colour-bank", "Stainer carton – black/white family", "% box", 30, 20, 100, "Store Manager", "Zone A – stainer shelf", "Keep cartons labelled and grouped by shade family."),
  make("luxol-under-200ml", "stainer-colour-bank", "Luxol enamel packs below 200 ml", "tin", 26, 20, 50, "Store Manager", "Zone B – mini Luxol cartons", "Only sub-200 ml packs; arrange by shade/code and keep labels visible."),
  make("colourant-vb", "stainer-colour-bank", "Colour-bank inlet VB", "% full", 55, 20, 100, "Staff", "Zone C – colour bank inlet VB", "Open the cap while making colour and confirm colourant is present."),
  make("colourant-c", "stainer-colour-bank", "Colour-bank inlet C", "% full", 40, 20, 100, "Staff", "Zone C – colour bank inlet C", "Check through the cap during colour preparation."),
  make("colourant-p", "stainer-colour-bank", "Colour-bank inlet P", "% full", 35, 20, 100, "Staff", "Zone C – colour bank inlet P"),
  make("colourant-f", "stainer-colour-bank", "Colour-bank inlet F", "% full", 22, 20, 100, "Staff", "Zone C – colour bank inlet F"),
  make("colourant-gc", "stainer-colour-bank", "Colour-bank inlet GC", "% full", 17, 20, 100, "Staff", "Zone C – colour bank inlet GC", "Below 20%: raise order/refill action."),
  make("colourant-re", "stainer-colour-bank", "Colour-bank inlet RE", "% full", 48, 20, 100, "Staff", "Zone C – colour bank inlet RE"),
  make("colourant-lm", "stainer-colour-bank", "Colour-bank inlet LM", "% full", 28, 20, 100, "Staff", "Zone C – colour bank inlet LM"),
  make("colourant-t", "stainer-colour-bank", "Colour-bank inlet T", "% full", 32, 20, 100, "Staff", "Zone C – colour bank inlet T"),
  make("colourant-cans-rack", "stainer-colour-bank", "Colourant cans on rack above machine", "can", 9, 8, 16, "Store Manager", "Zone C – rack above colour bank", "Keep correct colourant cans available, upright and labelled."),
  make("colour-bank-caps", "stainer-colour-bank", "Colour-bank caps clean and operational", "cap", 12, 12, 12, "Staff", "Zone C – machine inlets", "Caps must open, close and remain clearly labelled."),

  make("ext-flexo-large", "exterior-paint", "Long Life Flexo – large packs", "bucket", 3, 3, 6, "Store Manager", "Exterior rack – top row"),
  make("ext-flexo-small", "exterior-paint", "Long Life Flexo – small packs", "bucket", 2, 3, 8, "Store Manager", "Exterior rack – top row"),
  make("ext-antidust-large", "exterior-paint", "Weathercoat Anti Dust – large packs", "bucket", 7, 5, 12, "Store Manager", "Exterior rack – middle rows"),
  make("ext-antidust-small", "exterior-paint", "Weathercoat Anti Dust – small packs", "bucket", 8, 6, 16, "Store Manager", "Exterior rack – middle rows"),
  make("ext-glow", "exterior-paint", "Weathercoat exterior glow products", "bucket", 7, 5, 12, "Store Manager", "Exterior rack – middle rows"),
  make("ext-wallmasta", "exterior-paint", "Wallmasta exterior products", "bucket", 8, 6, 14, "Store Manager", "Exterior rack – lower-middle row"),
  make("primer-damp-shield", "exterior-paint", "Damp Shield primer", "bucket", 2, 3, 8, "Store Manager", "Exterior rack – bottom two rows", "Primer must remain only in the designated bottom two rows."),
  make("primer-seal-o-prime", "exterior-paint", "Seal-O-Prime / exterior primer", "bucket", 3, 3, 8, "Store Manager", "Exterior rack – bottom two rows"),
  make("primer-white", "exterior-paint", "White primer assorted packs", "bucket", 5, 4, 10, "Store Manager", "Exterior rack – bottom two rows"),

  make("silk-glamor", "interior-paint", "Silk Glamor", "bucket", 5, 4, 10, "Store Manager", "Interior rack – top row"),
  make("silk-glamor-hi-sheen", "interior-paint", "Silk Glamor Hi-Sheen", "bucket", 2, 3, 7, "Store Manager", "Interior rack – top row"),
  make("easy-clean-large", "interior-paint", "Easy Clean – large packs", "bucket", 5, 5, 12, "Store Manager", "Interior rack – upper-middle rows"),
  make("easy-clean-small", "interior-paint", "Easy Clean – small packs", "bucket", 5, 5, 14, "Store Manager", "Interior rack – upper-middle rows"),
  make("bison-glow-large", "interior-paint", "Bison Glow – large packs", "bucket", 5, 4, 10, "Store Manager", "Interior rack – lower-middle rows"),
  make("bison-glow-small", "interior-paint", "Bison Glow – small packs", "bucket", 6, 5, 14, "Store Manager", "Interior rack – lower-middle rows"),
  make("interior-silk", "interior-paint", "Other Silk interior products", "bucket", 7, 5, 12, "Store Manager", "Interior rack – bottom row"),

  make("roof-kool-seal-large", "waterproofing", "Roof Kool & Seal – large packs", "bucket", 3, 3, 7, "Store Manager", "Waterproofing rack – top row"),
  make("roof-kool-seal-small", "waterproofing", "Roof Kool & Seal – small packs", "bucket", 3, 4, 10, "Store Manager", "Waterproofing rack – top row"),
  make("dampstop-elasto-large", "waterproofing", "Dampstop Elasto – large packs", "bucket", 3, 3, 7, "Store Manager", "Waterproofing rack – middle row"),
  make("dampstop-elasto-small", "waterproofing", "Dampstop Elasto – small packs", "bucket", 2, 3, 8, "Store Manager", "Waterproofing rack – middle row"),
  make("dampstop-advanced", "waterproofing", "Dampstop Advanced", "bucket", 2, 2, 6, "Store Manager", "Waterproofing rack – middle row"),
  make("waterproofing-additive", "waterproofing", "Waterproofing liquid/additive", "can", 1, 2, 5, "Store Manager", "Waterproofing rack – middle row"),
  make("texture-sample-panels", "waterproofing", "Exterior texture sample panels", "panel", 22, 20, 28, "Store Manager", "Texture panel slots", "Keep panels upright, clean and in their assigned slots."),

  make("melamine-24-carat", "wood-finishes", "Woodkeeper Melamine 24 Carat kits", "kit", 10, 8, 16, "Store Manager", "Wood finishes rack – top row"),
  make("gp-thinner", "wood-finishes", "GP thinner", "bottle", 12, 10, 24, "Store Manager", "Wood finishes rack"),
  make("eco-thinner", "wood-finishes", "Eco thinner", "bottle", 2, 3, 8, "Store Manager", "Wood finishes rack"),
  make("crack-fill", "wood-finishes", "Crack fill", "tub", 5, 4, 10, "Store Manager", "Wood finishes rack"),
  make("sanding-sealer", "wood-finishes", "Sanding sealer", "tin", 5, 5, 12, "Store Manager", "Wood finishes rack"),
  make("car-patch", "wood-finishes", "Car patch / carpech", "tin", 3, 3, 8, "Store Manager", "Wood finishes rack"),
  make("local-turpentine", "wood-finishes", "Local turpentine oil", "bottle", 5, 5, 12, "Store Manager", "Wood finishes rack"),
  make("wood-stain", "wood-finishes", "Wood stain assorted shades", "tin", 8, 6, 16, "Store Manager", "Wood finishes rack"),
  make("wood-finish-other", "wood-finishes", "Other wood finish accessories", "unit", 4, 4, 10, "Store Manager", "Wood finishes rack"),

  make("level-plast", "bulk-materials", "Level plast", "bag", 8, 5, 15, "Store Manager", "Separate bulk-material area", "Check every day and do not mix with normal paint stock."),
  make("chalk-powder", "bulk-materials", "Chalk powder", "bag", 6, 5, 15, "Store Manager", "Separate bulk-material area"),
  make("putty-bag", "bulk-materials", "Putty", "bag", 12, 8, 25, "Store Manager", "Separate bulk-material area"),
  make("white-cement", "bulk-materials", "White cement", "bag", 5, 5, 15, "Store Manager", "Separate bulk-material area"),
  make("whiting", "bulk-materials", "Whiting", "bag", 4, 5, 15, "Store Manager", "Separate bulk-material area"),
  make("pop", "bulk-materials", "POP", "bag", 10, 7, 20, "Store Manager", "Separate bulk-material area"),
  make("wax", "bulk-materials", "Wax", "pack", 3, 3, 10, "Store Manager", "Separate bulk-material area"),
  make("chowry", "bulk-materials", "Chowry", "unit", 2, 3, 8, "Store Manager", "Separate bulk-material area"),
  make("texture-putty", "bulk-materials", "Texture putty", "bag", 4, 6, 18, "Store Manager", "Separate bulk-material area", "Daily stock evaluation is mandatory."),

  make("desk-pen", "desk", "Working pens", "pcs", 4, 3, 10, "Staff", "Working desk"),
  make("desk-marker", "desk", "Permanent markers", "pcs", 1, 2, 6, "Staff", "Working desk"),
  make("desk-stapler", "desk", "Desk stapler", "pcs", 1, 1, 2, "Staff", "Working desk"),
  make("desk-calculator", "desk", "Calculator", "pcs", 1, 1, 2, "Staff", "Working desk"),
  make("estimate-pad", "desk", "Estimate pad", "pad", 2, 2, 5, "Staff", "Working desk"),
  make("bill-book", "desk", "Bill book", "book", 1, 1, 3, "Staff", "Working desk"),

  make("cash-100", "cash-token", "₹100 change notes", "notes", 4, 5, 15, "Store Manager", "Cash drawer"),
  make("cash-50", "cash-token", "₹50 change notes", "notes", 8, 10, 25, "Store Manager", "Cash drawer"),
  make("cash-20", "cash-token", "₹20 change notes", "notes", 15, 20, 50, "Store Manager", "Cash drawer"),
  make("cash-10", "cash-token", "₹10 change notes", "notes", 25, 30, 75, "Store Manager", "Cash drawer"),
  make("token-cash", "cash-token", "Cash tokens", "pcs", 35, 20, 60, "Store Manager", "Token box"),
  make("token-points", "cash-token", "Point tokens", "pcs", 12, 20, 60, "Store Manager", "Token box", "Point token must be stapled with each applicable cash token."),
  make("token-diary", "cash-token", "Token customer diary", "book", 1, 1, 2, "Store Manager", "Token box", "Record name and mobile when points token is unavailable or ₹10–₹20 is adjusted."),

  make("extra-pen", "stationery", "Extra pens", "pcs", 8, 5, 20, "Staff", "Stationery drawer"),
  make("punch", "stationery", "Paper punch", "pcs", 1, 1, 2, "Staff", "Stationery drawer"),
  make("extra-stapler", "stationery", "Backup stapler", "pcs", 1, 1, 2, "Staff", "Stationery drawer"),
  make("stapler-pin", "stationery", "Stapler pin boxes", "box", 2, 3, 10, "Staff", "Stationery drawer"),
  make("stamp", "stationery", "Store stamp", "pcs", 1, 1, 2, "Staff", "Stationery drawer"),
  make("new-copy", "stationery", "New notebooks", "pcs", 2, 3, 10, "Staff", "Stationery drawer"),

  make("poly-small", "polybag", "Small poly bags", "pcs", 75, 50, 200, "Store Manager", "Packaging drawer"),
  make("poly-medium", "polybag", "Medium poly bags", "pcs", 30, 50, 200, "Store Manager", "Packaging drawer"),
  make("poly-large", "polybag", "Large poly bags", "pcs", 20, 30, 100, "Store Manager", "Packaging drawer"),

  make("rental-register", "rental", "Rental register book", "book", 1, 1, 2, "Store Manager", "Register drawer"),
  make("rental-pending", "rental", "Pending rental entries", "entry", 3, 0, 0, "Store Manager", "Register drawer"),

  make("gst-invoices", "invoices", "Unfiled GST invoices", "invoice", 6, 0, 0, "Accounts", "Invoice drawer"),
  make("temporary-bills", "invoices", "Unentered temporary bills", "bill", 4, 0, 0, "Accounts", "Invoice drawer"),
  make("missing-docs", "invoices", "Purchases missing invoice record", "purchase", 1, 0, 0, "Accounts", "Invoice drawer", "Create a temporary invoice containing vendor, date, articles, amount and payment mode/account."),

  ...["9 in Exterior roller", "9 in Interior roller", "6 in roller", "4 in roller", "2 in roller", "9 in refill", "6 in refill", "4 in refill", "2 in refill"].map((name, i) => make(`roller-${i}`, "rollers", name, "pcs", i === 2 ? 1 : 4, 2, 8, "Store Manager", "Roller rack")),

  ...[120, 150, 180, 220, 240, 280].map((grit, i) => make(`sand-${grit}`, "brushes", `Wet & dry sandpaper ${grit} grit`, "sheet", i === 3 ? 6 : 15, 10, 40, "Store Manager", "Sandpaper boxes")),
  ...["4 in brush", "3 in brush", "2.5 in brush", "2 in brush", "1.5 in brush", "1 in brush", "Kalam brush"].map((name, i) => make(`brush-${i}`, "brushes", name, "pcs", i === 0 ? 2 : 6, 3, 12, "Store Manager", "Brush rack")),
  ...[8, 6, 5, 4, 3, 2, 1].map((size, i) => make(`blade-${size}`, "brushes", `${size} in putty blade`, "pcs", i === 1 ? 1 : 4, 2, 8, "Store Manager", "Lower brush rack")),

  ...[80, 100, 120, 150].map((grit, i) => make(`roll-${grit}`, "rolls-stencils", `Abrasive roll ${grit} grit`, "roll", i === 0 ? 1 : 3, 2, 6, "Store Manager", "Wall roll rod")),
  make("wood-roll-80", "rolls-stencils", "Wood abrasive roll 80 grit", "roll", 2, 2, 5, "Store Manager", "Wall roll rod"),
  make("wood-roll-60", "rolls-stencils", "Wood abrasive roll 60 grit", "roll", 1, 2, 5, "Store Manager", "Wall roll rod"),
  make("stencils", "rolls-stencils", "Stencil sheets", "pcs", 12, 10, 30, "Store Manager", "Stencil hanger"),
  make("red-cord", "rolls-stencils", "Red marking cord (lal chari)", "roll", 1, 2, 5, "Store Manager", "Stencil area")
];

export const dailyTasks = [
  { id: "m-books", shift: "morning", title: "Shade books and fan deck", description: "Interior, exterior, texture and enamel books, colour palettes and fan deck are present, clean and arranged.", owner: "Store Manager", categoryId: "books", evidenceRequired: true },
  { id: "m-desk", shift: "morning", title: "Working desk readiness", description: "Pens, markers, calculator, stapler, estimate pad, bill book and laptop are ready for use.", owner: "Staff", categoryId: "desk", evidenceRequired: true },
  { id: "m-cash", shift: "morning", title: "Cash change and token box", description: "₹100, ₹50, ₹20 and ₹10 notes are available; cash tokens, point tokens and diary are reconciled.", owner: "Store Manager", categoryId: "cash-token" },
  { id: "m-stationery", shift: "morning", title: "Stationery drawer", description: "Extra pens, punch, stapler, pins, stamp and notebooks are available.", owner: "Staff", categoryId: "stationery" },
  { id: "m-poly", shift: "morning", title: "Polybag stock", description: "Small, medium and large polybags are available in sufficient quantity.", owner: "Store Manager", categoryId: "polybag" },
  { id: "m-rental", shift: "morning", title: "Rental register", description: "Pending rental entries are updated in the physical book until app migration is complete.", owner: "Store Manager", categoryId: "rental" },
  { id: "m-invoices", shift: "morning", title: "Pending bills and invoices", description: "GST invoices, temporary bills and missing purchase records are checked and moved through the filing workflow.", owner: "Accounts", categoryId: "invoices" },
  { id: "m-vyapar", shift: "morning", title: "Vyapar duplicate-control check", description: "Before sales or purchase entry, search the existing item and party. Never create spelling, size, local-name or family-member duplicates.", owner: "Store Manager" },
  { id: "m-bulk-materials", shift: "morning", title: "Daily bulk-material stock", description: "Check level plast, chalk powder, putty, white cement, whiting, POP, wax, chowry and texture putty separately every day.", owner: "Store Manager", categoryId: "bulk-materials" },
  { id: "m-rollers", shift: "morning", title: "Rollers and refills", description: "2, 4, 6 and 9 inch rollers and refills are sorted and counted.", owner: "Store Manager", categoryId: "rollers", evidenceRequired: true },
  { id: "m-brushes", shift: "morning", title: "Brushes, sandpaper and patti", description: "Brushes, kalam brushes, wet/dry sandpaper and putty blades are sorted by size and grit.", owner: "Store Manager", categoryId: "brushes", evidenceRequired: true },
  { id: "m-rolls", shift: "morning", title: "Abrasive rolls and stencils", description: "60–150 grit rolls, wooden rolls, stencils and lal chari are available and arranged.", owner: "Store Manager", categoryId: "rolls-stencils", evidenceRequired: true },
  { id: "a-enamel", shift: "afternoon", title: "Enamel and Luxol display", description: "Luxol and other enamel products are arranged by type and pack size; printer supplies and nearby files are checked.", owner: "Store Manager", categoryId: "enamel", evidenceRequired: true },
  { id: "a-stainer-colour-bank", shift: "afternoon", title: "Stainer, mini Luxol and colour bank", description: "Zone A stainer cartons are checked by remaining percentage and anything below 20% is entered in the order book. Zone B Luxol packs below 200 ml are sorted. Zone C colour-bank inlets are checked by opening caps while making colour, and colourant cans above the machine are available.", owner: "Store Manager", categoryId: "stainer-colour-bank", evidenceRequired: true },
  { id: "a-exterior", shift: "afternoon", title: "Exterior paint rack", description: "Exterior products are sorted by family and pack size. Primers remain in the bottom two rows.", owner: "Store Manager", categoryId: "exterior-paint", evidenceRequired: true },
  { id: "a-interior", shift: "afternoon", title: "Interior paint rack", description: "Interior paints are sorted by product family, finish and pack size with labels facing out.", owner: "Store Manager", categoryId: "interior-paint", evidenceRequired: true },
  { id: "a-waterproofing", shift: "afternoon", title: "Waterproofing rack", description: "Roof Kool & Seal, Dampstop and related products are fully displayed and shortages recorded.", owner: "Store Manager", categoryId: "waterproofing", evidenceRequired: true },
  { id: "a-wood", shift: "afternoon", title: "Wood finish section", description: "Melamine, GP thinner, Eco thinner, crack fill, sanding sealer, car patch and turpentine are checked and arranged.", owner: "Store Manager", categoryId: "wood-finishes", evidenceRequired: true },
  { id: "e-charge", shift: "evening", title: "Charge store devices", description: "All required phones, tablets and store devices are connected to working chargers before leaving.", owner: "Staff", categoryId: "enamel" },
  { id: "e-cash", shift: "evening", title: "Count and match cash", description: "Cash is counted and matched; unresolved token adjustments are entered in the diary.", owner: "Store Manager" },
  { id: "e-bills", shift: "evening", title: "File today’s bills", description: "Entered bills are filed and unentered documents remain in the pending drawer.", owner: "Accounts", categoryId: "invoices" },
  { id: "e-order", shift: "evening", title: "Prepare tomorrow’s order list", description: "Low-stock and out-of-stock items are reviewed and reorder actions are raised.", owner: "Store Manager" },
  { id: "e-clean", shift: "evening", title: "Clean counter and displays", description: "Counter, desk, catalogues and product racks are left clean and properly arranged.", owner: "Staff", evidenceRequired: true },
  { id: "e-power", shift: "evening", title: "Electrical closing check", description: "Printer, lights, AC and other equipment are switched off as required; charging board remains safely in use.", owner: "Store Manager" },
  { id: "e-lock", shift: "evening", title: "Lock and close store", description: "Final walk-through is complete and the store is securely locked.", owner: "Store Manager" }
] satisfies import("./types").DailyTask[];
